### ISSUE TITLE
find browser Chrome failed, profile folder is not exist

### ISSUE THREAD

**Issue by Amir-78** [moonD4rk/HackBrowserData#134]
**Describe the bug**
`./hack-browser-data -vv` :

```
[NOTICE] [browser.go:46,pickChromium] find browser OperaGX failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser CocCoc failed, profile folder is not exist
[INFO] [chromium.go:89,getItemPath] Brave profile parentDir: C:\Users\User\AppData\Local\BraveSoftware\Brave-Browser\User Data
[INFO] [chromium.go:90,getItemPath] Brave profile baseDir: Default
[NOTICE] [browser.go:50,pickChromium] find browser Brave success
[NOTICE] [browser.go:46,pickChromium] find browser QQ failed, profile folder is not exist
[INFO] [chromium.go:89,getItemPath] Microsoft Edge profile parentDir: C:\Users\User\AppData\Local\Microsoft\Edge\User Data
[INFO] [chromium.go:90,getItemPath] Microsoft Edge profile baseDir: Default
[NOTICE] [browser.go:50,pickChromium] find browser Microsoft Edge success
[NOTICE] [browser.go:46,pickChromium] find browser Opera failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser Chrome Beta failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser Vivaldi failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser Yandex failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser 360speed failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser Chrome failed, profile folder is not exist
[NOTICE] [browser.go:46,pickChromium] find browser Chromium failed, profile folder is not exist
```
- **Cannot find Chrome folder: `find browser Chrome failed, profile folder is not exist`**
     - My Chrome Version: **`101.0.4951.54 (Official Build) (64-bit)`**
     
- **Cannot find Chromium folder: `find browser Chromium failed, profile folder is not exist`**

- **Cannot find OperaGX folder: `find browser OperaGX failed, profile folder is not exist`**
     - My OperaGX Version: **`LVL3 (core: 77.0.4054.298)`**
     
**Desktop (please complete the following information):**
 - OS Name: `Windows 8.1 Pro`
 - Browser Name 1: `Chrome `
 - Browser Version 1: `101.0.4951.54 (Official Build) (64-bit)`
  - Browser Name 2: `OperaGX`
 - Browser Version 2: `LVL3 (core: 77.0.4054.298)`

**Additional context**
Browsers profile folders are not recognized even though I use them and all data is saved in them.

**Comment by moonD4rk** [comment]
You can use custom profile folder path. for example,  enter `chrome://version` in your address bar
![image](https://user-images.githubusercontent.com/24284231/168072376-07fcdb28-1492-4469-8ff1-91fe22eb9c69.png)
then use this command 
```
./hack-browser-data -b chrome -p "C:\Users\Lori\AppData\Local\Google\Chrome\User Data\Profile 3"
```
for OperaGX's profile path maybe is `about://about`

```
./hack-browser-data -b opera-gx -p "C://opera-gx/profile path"
```

**Comment by Amir-78** [comment]
> You can use custom profile folder path. for example, enter `chrome://version` in your address bar ![image](https://user-images.githubusercontent.com/24284231/168072376-07fcdb28-1492-4469-8ff1-91fe22eb9c69.png) then use this command
> 
> ```
> ./hack-browser-data -b chrome -p "C:\Users\Lori\AppData\Local\Google\Chrome\User Data\Profile 3"
> ```
> 
> for OperaGX's profile path maybe is `about://about`
> 
> ```
> ./hack-browser-data -b opera-gx -p "C://opera-gx/profile path"
> ```

yes, I know about the custom profile folder path, but the old version of HackBrowserData detects it auto so I guess it is better to be in this version too.

**Comment by moonD4rk** [comment]
> > @Amir-78 ok, I will try fix it.
> 
> Thank you <3

Can you tell me what's your browser profile path？

**Comment by Amir-78** [comment]
> > > @Amir-78 ok, I will try fix it.
> > 
> > 
> > Thank you <3
> 
> Can you tell me what's your browser profile path？

@moonD4rk `C:\Users\AmirDev\AppData\Local\Google\Chrome\User Data\Profile 1`

**Comment by Amir-78** [comment]
@moonD4rk 
Did you find a way to solve the bug? if no I can give you my own suggestion, which I think is really appropriate?

**Comment by moonD4rk** [comment]
Very happy to hear your suggestios. @Amir-78

**Comment by Amir-78** [comment]
@moonD4rk Alright, so instead of setting the **default profile path**, you need to filter all directories in `/Chrome/User Data/` and show only the directories that include `Login Data` file and make sure the directory is not `System Profile` because its not useful `(The System Profile is a built-in-with-Chrome profile that backs the User Manager. Users do not use it for actual browsing; it provides a Profile for the User Manager (switch person window) only.)`, because when a login by his google account to chrome and sync his data the default profile path will be changed to `Profile 1`, and also by this method you can extract all the accounts from all user profiles.

- **Javascript Example Code:**
```javascript
//Windows;

const fs = require('fs');

let homeDir = `C:/Users/${require("os").userInfo().username}`

let chromeProfilesPath = homeDir + "/AppData/Local/Google/Chrome/User Data/"

let chromeProfiles = [];

//Show all dirs in chromeProfilesPath;

fs.readdir(chromeProfilesPath, function (err, dirs) {
    //Filter all directories in chromeProfilesPath and show only the directory who includes "Login Data" file!

    dirs = dirs.filter(dir => fs.existsSync(`${chromeProfilesPath}${dir}/Login\ Data`) && dir != "System Profile")
    // Push results to chromeProfiles;
    for (var i = 0; i < dirs.length; i++) {
        chromeProfiles.push(`${chromeProfilesPath}/${dirs[i]}`)
    }

    //Show extracted profiles!
    console.log(chromeProfiles)
});
```

And to extract all the data from all the profiles you can use:

- access all the extracted profiles and extract the data one by one:
```js
    for (var i = 0; i < chromeProfiles.length; i++) {
        console.log(`Getting Data from ${chromeProfiles[i]}`);
        extractData(chromeProfiles[i])// Your extractData function;
    }
```

**Comment by moonD4rk** [comment]
@Amir-78 Thx, this makes perfect sense and I will try to refactor the code using this approach.

**Comment by Amir-78** [comment]
@moonD4rk Alright, if you need any help feel free to contact me. <3

**Comment by Amir-78** [comment]
@moonD4rk fixed here (#138 )

**Comment by batool78692110** [comment]
wah amir 78

**Comment by Amir-78** [comment]
> wah amir 78

:)

**Comment by moonD4rk** [comment]
Hi @Amir-78 , i think this issuse has been fixed in v0.4.3, please check

**Comment by Amir-78** [comment]
@moonD4rk still not working, have you used my PR ?  ![Img](https://cdn.discordapp.com/attachments/790332165447221279/983085327688290354/unknown.png)

**Comment by moonD4rk** [comment]
@Amir-78 Test fine on macOS and Linux, I'll find a Windows computer later to try
